name: fast_router
description: A router management, based on the modified version of fluro, adds more convenient extension function and global implementation without context jump
version: 2.0.1
homepage: https://github.com/StrangerKjq/fast_router

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: